### PR TITLE
Implemented sorting algorithms in JS

### PR DESCRIPTION
**Pull request by saurabh47**
- moved selection & bubble sort into sorting directory
- added merge & quick sort
- added selection & insertion sort

### CODE REVIEW

**Comment by saurabh47** [comment]
@maheshmnj @TamtePrathamesh Review the PR

**Comment by maheshmnj** [comment]
Will reave this soon

**Comment by maheshmnj** [comment]
We should add a Single Readme file under the Sorting directory to briefly explain how each sorting algorithm works.

**Comment by maheshmnj** [comment]
Now that we have a organized repository we should move the javascript implementation in sort directory https://github.com/saurabh47/Popular_Coding_Questions_Solution/tree/master/algorithms/sort

The further implementation requires addressing https://github.com/saurabh47/Popular_Coding_Questions_Solution/issues/25

**Pull request merged**
