### PR TITLE
Implement graph data structures and traversal

### PR DESCRIPTION
**Pull request by maheshmnj**
Adds an adjacency list for a simple case for graphs like this 

```
0 --- 1
 |    /
 |  /
 2  - - - 3
``` 
But this would fail for random numbers (WIth index out-of range error) Because we only allocate an array of length 4.(since we only have 4 nodes in the array). 

```
5 --- 4
 |    /
 |  /
 2  - - - 3
```

### CODE REVIEW

**Comment by maheshmnj** [comment]
@saurabh47 I think the solution for this issue is to create another array of length 4 that stores the values of all 4 nodes, What do you think?

**Comment by maheshmnj** [comment]
I have submitted a change is that the correct way to solve this issue?

**Comment by saurabh47** [comment]
- For adjacency list we should use Hashmap data type
- For adjacency matrix we should use Array datatype

**Comment by maheshmnj** [comment]
submitted the change

**Comment by saurabh47** [comment]
let me know once your changes finalize @maheshmnj

**Comment by maheshmnj** [comment]
This is ready to merge @saurabh47

**Comment by maheshmnj** [comment]
Also let me know if you have any topics in mind that needs to be added.
I just realized the [adjacency_list implementation](https://github.com/saurabh47/Popular_Coding_Questions_Solution/blob/e83407735efe14c33def821d750c8d23ac3814f2/data_structures/graphs/adjacency_list.py) should also implement a function to show "if path exists between two nodes."

**Pull request merged**
