### PR TITLE
Create Find-Majority-Element(Moore's-Voting-Algorithm)

### PR DESCRIPTION
**Pull request by nishantagrawal01**

### CODE REVIEW

**Comment by maheshmnj** [comment]
Hi @nishantagrawal01, thanks for your contribution.
Please consider updating the readme explaining what this algorithm does.
cc: @saurabh47 

Thanks

**Comment by saurabh47** [comment]
Hi @nishantagrawal01, thanks for your contribution.
Please, follow the proper naming conversion & directory structure.
In your case, create a directory with the name ` find_majority_element`. 
In that directory create file name `moores_voting_algorithm.c` file with your code.

**Comment by nishantagrawal01** [comment]
> Hi @nishantagrawal01, thanks for your contribution. Please consider updating the readme explaining what this algorithm does. cc: @saurabh47
> 
> Thanks

Hi @maheshmnj, 

Thanks for the info. I have made relevant changes and updated the Pull request. Please merge the same. Thanks a lot for heads up.

**Comment by nishantagrawal01** [comment]
> Hi @nishantagrawal01, thanks for your contribution. Please, follow the proper naming conversion & directory structure. In your case, create a directory with the name ` find_majority_element`. In that directory create file name `moores_voting_algorithm.c` file with your code.

Hi @saurabh47,

Thanks for the info. I have made relevant changes and updated the Pull request. Please merge the same. Thanks a lot for heads up.

**Comment by nishantagrawal01** [comment]
Hi @saurabh47 @maheshmnj ,

Thanks for the info. I have made relevant changes and updated the Pull request. Please merge the same. Thanks a lot for heads up.

**Pull request merged**
