### PR TITLE
Organize Repo structure

### PR DESCRIPTION
**Pull request by maheshmnj**
Addresses https://github.com/saurabh47/Popular_Coding_Questions_Solution/issues/24

### CODE REVIEW

**Comment by maheshmnj** [comment]
cc: @saurabh47

**Comment by maheshmnj** [comment]
The readme needs to be improved still. Will update it soon.

**Comment by saurabh47** [comment]
@maheshmnj I have renamed the PR title with [WIP] (work in progress). Once your changes are finalised remove that [WIP] & tag me. I will review your PR.

**Comment by maheshmnj** [comment]
Sounds Good

**Comment by maheshmnj** [comment]
@saurabh47 I think we can merge this and continue organizing on top of this wdyt?

**Pull request merged**
