### PR TITLE
caesar-cipher

### PR DESCRIPTION
**Pull request by Aditya489**
caesarcipher py - Popular_Coding_Questions_Solution - Visual Studio Code 08-10-2020 23_20_49

 If we see this encryption technique in mathematical way then the formula to get encrypted letter will be:

c = (x + n) mod 26

where, c is place value of encrypted letter,

x is place value of actual letter,

n is the number that shows us how many positions of letters we have to replace.

On other hand, to decrypt each letter we’ll use the formula given below:

c = (x – n) mod 26

### CODE REVIEW

**Review by saurabh47 — CHANGES_REQUESTED** [review]
* Move you code to `caesar-cipher` directory.
* No need to add screenshots of your vscode. if you want you can send us online editors links .https://repl.it/

**Comment by Aditya489** [comment]
Can I rename the file to caesar-cipher.py and can you then merge it cause I'm new here and getting used to the GitHub interface! So can you then merge it?

**Comment by saurabh47** [comment]
you have renamed the file.
Now move that file to `caesar-cipher` directory locally.Then commit the changes & push.

**Comment by Aditya489** [comment]
There was some error while pushing up the file so I kind of had to upload it! Can't it be merged like this? Even my other pull request have been merged like that! Ok but still let me try

**Comment by saurabh47** [comment]
Please try to move your code to  `caesar-cipher` directory.If you face some issue.let me know.

**Pull request closed without merging**
